import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { Navbar, ArtCard, Map } from '../components';
import { getArts } from '../services';

export default function Home({ arts }) {
  console.log(arts);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        {arts.map((art) => (
          <ArtCard art={art.node} />
        ))}
      </div>
      <Navbar />
      <h2>Location</h2>
      <Map arts={arts}/>
    </div>
  );
}

export async function getStaticProps() {
  const arts = (await getArts()) || [];

  return {
    props: { arts },
  };
}
