/* eslint-disable react/button-has-type */
import Head from 'next/head';
import React, { useState } from 'react';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import { ShowMarkers, ArtWidget, MapView } from '../components';

import { Navbar, ArtCard, Map } from '../components';

import { getArts } from '../services';
import MapPopup from '../components/MapPopup';

// eslint-disable-next-line react/prop-types
export default function Home({ arts }) {
  console.log(arts);
  const [selectedArt, setSelectedArt] = useState(null);
  const onMarkerClick = (e) => {
    setSelectedArt(e);
  };

  const [showContent, setShowContent] = useState(false);

  const onShowContentClick = (e) => {
    setShowContent((prev) => !prev);
  };

  return (
    <div className={styles.mainContainer}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={
          showContent
            ? `${styles.contentContainer} ${styles.showContent} `
            : `${styles.contentContainer}`
        }
      >
        <ArtWidget />
      </div>
      <div className={styles.mapContainer}>
        <MapView>
          <button
            onClick={(e) => onShowContentClick(e)}
            className={styles.mapButton}
          >
            {showContent ? 'Map View' : 'List View'}
          </button>
          <ShowMarkers
            selectedArt={selectedArt}
            data={arts}
            onClick={(e) => onMarkerClick(e)}
          />
          {selectedArt && <MapPopup art={selectedArt} />}
        </MapView>
      </div>

      <Navbar />
      <h2>Location</h2>
      <Map arts={arts}/>

    </div>
  );
}

export async function getStaticProps() {
  const arts = (await getArts()) || [];

  return {
    props: { arts },
  };
}
