import React from 'react';
import Head from 'next/head';
import MapView from '../components/MapView';
import { getArts } from '../services';

export default function Map({ arts }) {
  arts.map((art) => console.log(art.node));

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Something
      <MapView>{/* space for markers */}</MapView>
    </div>
  );
}

export async function getStaticProps() {
  const arts = (await getArts()) || [];

  return {
    props: { arts },
  };
}
